/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as VipBonusRouteImport } from './routes/vip-bonus'
import { Route as TreasureBoxRouteImport } from './routes/treasure-box'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TestHeadersRouteImport } from './routes/test-headers'
import { Route as TeamViewRouteImport } from './routes/team-view'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IncomeDetailsRouteImport } from './routes/income-details'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as AppDownloadRouteImport } from './routes/app-download'
import { Route as AddBankRouteImport } from './routes/add-bank'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VipBonusRoute = VipBonusRouteImport.update({
  id: '/vip-bonus',
  path: '/vip-bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasureBoxRoute = TreasureBoxRouteImport.update({
  id: '/treasure-box',
  path: '/treasure-box',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHeadersRoute = TestHeadersRouteImport.update({
  id: '/test-headers',
  path: '/test-headers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamViewRoute = TeamViewRouteImport.update({
  id: '/team-view',
  path: '/team-view',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeDetailsRoute = IncomeDetailsRouteImport.update({
  id: '/income-details',
  path: '/income-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDownloadRoute = AppDownloadRouteImport.update({
  id: '/app-download',
  path: '/app-download',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBankRoute = AddBankRouteImport.update({
  id: '/add-bank',
  path: '/add-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank': typeof AddBankRoute
  '/app-download': typeof AppDownloadRoute
  '/channel': typeof ChannelRoute
  '/income-details': typeof IncomeDetailsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/team-view': typeof TeamViewRoute
  '/test-headers': typeof TestHeadersRoute
  '/transactions': typeof TransactionsRoute
  '/treasure-box': typeof TreasureBoxRoute
  '/vip-bonus': typeof VipBonusRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank': typeof AddBankRoute
  '/app-download': typeof AppDownloadRoute
  '/channel': typeof ChannelRoute
  '/income-details': typeof IncomeDetailsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/team-view': typeof TeamViewRoute
  '/test-headers': typeof TestHeadersRoute
  '/transactions': typeof TransactionsRoute
  '/treasure-box': typeof TreasureBoxRoute
  '/vip-bonus': typeof VipBonusRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank': typeof AddBankRoute
  '/app-download': typeof AppDownloadRoute
  '/channel': typeof ChannelRoute
  '/income-details': typeof IncomeDetailsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/team-view': typeof TeamViewRoute
  '/test-headers': typeof TestHeadersRoute
  '/transactions': typeof TransactionsRoute
  '/treasure-box': typeof TreasureBoxRoute
  '/vip-bonus': typeof VipBonusRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-bank'
    | '/app-download'
    | '/channel'
    | '/income-details'
    | '/invite'
    | '/leaderboard'
    | '/login'
    | '/mission'
    | '/profile'
    | '/recharge'
    | '/redeem'
    | '/register'
    | '/team'
    | '/team-view'
    | '/test-headers'
    | '/transactions'
    | '/treasure-box'
    | '/vip-bonus'
    | '/withdraw'
    | '/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-bank'
    | '/app-download'
    | '/channel'
    | '/income-details'
    | '/invite'
    | '/leaderboard'
    | '/login'
    | '/mission'
    | '/profile'
    | '/recharge'
    | '/redeem'
    | '/register'
    | '/team'
    | '/team-view'
    | '/test-headers'
    | '/transactions'
    | '/treasure-box'
    | '/vip-bonus'
    | '/withdraw'
    | '/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-bank'
    | '/app-download'
    | '/channel'
    | '/income-details'
    | '/invite'
    | '/leaderboard'
    | '/login'
    | '/mission'
    | '/profile'
    | '/recharge'
    | '/redeem'
    | '/register'
    | '/team'
    | '/team-view'
    | '/test-headers'
    | '/transactions'
    | '/treasure-box'
    | '/vip-bonus'
    | '/withdraw'
    | '/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddBankRoute: typeof AddBankRoute
  AppDownloadRoute: typeof AppDownloadRoute
  ChannelRoute: typeof ChannelRoute
  IncomeDetailsRoute: typeof IncomeDetailsRoute
  InviteRoute: typeof InviteRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MissionRoute: typeof MissionRoute
  ProfileRoute: typeof ProfileRoute
  RechargeRoute: typeof RechargeRoute
  RedeemRoute: typeof RedeemRoute
  RegisterRoute: typeof RegisterRoute
  TeamRoute: typeof TeamRoute
  TeamViewRoute: typeof TeamViewRoute
  TestHeadersRoute: typeof TestHeadersRoute
  TransactionsRoute: typeof TransactionsRoute
  TreasureBoxRoute: typeof TreasureBoxRoute
  VipBonusRoute: typeof VipBonusRoute
  WithdrawRoute: typeof WithdrawRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-bonus': {
      id: '/vip-bonus'
      path: '/vip-bonus'
      fullPath: '/vip-bonus'
      preLoaderRoute: typeof VipBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasure-box': {
      id: '/treasure-box'
      path: '/treasure-box'
      fullPath: '/treasure-box'
      preLoaderRoute: typeof TreasureBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-headers': {
      id: '/test-headers'
      path: '/test-headers'
      fullPath: '/test-headers'
      preLoaderRoute: typeof TestHeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-view': {
      id: '/team-view'
      path: '/team-view'
      fullPath: '/team-view'
      preLoaderRoute: typeof TeamViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-details': {
      id: '/income-details'
      path: '/income-details'
      fullPath: '/income-details'
      preLoaderRoute: typeof IncomeDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-download': {
      id: '/app-download'
      path: '/app-download'
      fullPath: '/app-download'
      preLoaderRoute: typeof AppDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-bank': {
      id: '/add-bank'
      path: '/add-bank'
      fullPath: '/add-bank'
      preLoaderRoute: typeof AddBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddBankRoute: AddBankRoute,
  AppDownloadRoute: AppDownloadRoute,
  ChannelRoute: ChannelRoute,
  IncomeDetailsRoute: IncomeDetailsRoute,
  InviteRoute: InviteRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MissionRoute: MissionRoute,
  ProfileRoute: ProfileRoute,
  RechargeRoute: RechargeRoute,
  RedeemRoute: RedeemRoute,
  RegisterRoute: RegisterRoute,
  TeamRoute: TeamRoute,
  TeamViewRoute: TeamViewRoute,
  TestHeadersRoute: TestHeadersRoute,
  TransactionsRoute: TransactionsRoute,
  TreasureBoxRoute: TreasureBoxRoute,
  VipBonusRoute: VipBonusRoute,
  WithdrawRoute: WithdrawRoute,
  WithdrawalsRoute: WithdrawalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
