/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as VipBonusRouteImport } from './routes/vip-bonus'
import { Route as TreasureBoxRouteImport } from './routes/treasure-box'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TestHeadersRouteImport } from './routes/test-headers'
import { Route as TeamViewRouteImport } from './routes/team-view'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IncomeDetailsRouteImport } from './routes/income-details'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as AppDownloadRouteImport } from './routes/app-download'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddBankRouteImport } from './routes/add-bank'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSlidersRouteImport } from './routes/admin.sliders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminRedeemCodesRouteImport } from './routes/admin.redeem-codes'
import { Route as AdminRechargesRouteImport } from './routes/admin.recharges'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGatewaysRouteImport } from './routes/admin.gateways'

const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VipBonusRoute = VipBonusRouteImport.update({
  id: '/vip-bonus',
  path: '/vip-bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasureBoxRoute = TreasureBoxRouteImport.update({
  id: '/treasure-box',
  path: '/treasure-box',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHeadersRoute = TestHeadersRouteImport.update({
  id: '/test-headers',
  path: '/test-headers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamViewRoute = TeamViewRouteImport.update({
  id: '/team-view',
  path: '/team-view',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeDetailsRoute = IncomeDetailsRouteImport.update({
  id: '/income-details',
  path: '/income-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDownloadRoute = AppDownloadRouteImport.update({
  id: '/app-download',
  path: '/app-download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBankRoute = AddBankRouteImport.update({
  id: '/add-bank',
  path: '/add-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlidersRoute = AdminSlidersRouteImport.update({
  id: '/sliders',
  path: '/sliders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedeemCodesRoute = AdminRedeemCodesRouteImport.update({
  id: '/redeem-codes',
  path: '/redeem-codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargesRoute = AdminRechargesRouteImport.update({
  id: '/recharges',
  path: '/recharges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGatewaysRoute = AdminGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank': typeof AddBankRoute
  '/admin': typeof AdminRouteWithChildren
  '/app-download': typeof AppDownloadRoute
  '/channel': typeof ChannelRoute
  '/income-details': typeof IncomeDetailsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/team-view': typeof TeamViewRoute
  '/test-headers': typeof TestHeadersRoute
  '/transactions': typeof TransactionsRoute
  '/treasure-box': typeof TreasureBoxRoute
  '/vip-bonus': typeof VipBonusRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/redeem-codes': typeof AdminRedeemCodesRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank': typeof AddBankRoute
  '/app-download': typeof AppDownloadRoute
  '/channel': typeof ChannelRoute
  '/income-details': typeof IncomeDetailsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/team-view': typeof TeamViewRoute
  '/test-headers': typeof TestHeadersRoute
  '/transactions': typeof TransactionsRoute
  '/treasure-box': typeof TreasureBoxRoute
  '/vip-bonus': typeof VipBonusRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/redeem-codes': typeof AdminRedeemCodesRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank': typeof AddBankRoute
  '/admin': typeof AdminRouteWithChildren
  '/app-download': typeof AppDownloadRoute
  '/channel': typeof ChannelRoute
  '/income-details': typeof IncomeDetailsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/team-view': typeof TeamViewRoute
  '/test-headers': typeof TestHeadersRoute
  '/transactions': typeof TransactionsRoute
  '/treasure-box': typeof TreasureBoxRoute
  '/vip-bonus': typeof VipBonusRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/redeem-codes': typeof AdminRedeemCodesRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-bank'
    | '/admin'
    | '/app-download'
    | '/channel'
    | '/income-details'
    | '/invite'
    | '/leaderboard'
    | '/login'
    | '/mission'
    | '/profile'
    | '/recharge'
    | '/redeem'
    | '/register'
    | '/team'
    | '/team-view'
    | '/test-headers'
    | '/transactions'
    | '/treasure-box'
    | '/vip-bonus'
    | '/withdraw'
    | '/withdrawals'
    | '/admin/gateways'
    | '/admin/login'
    | '/admin/members'
    | '/admin/payouts'
    | '/admin/plans'
    | '/admin/recharges'
    | '/admin/redeem-codes'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/transactions'
    | '/admin/withdrawals'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-bank'
    | '/app-download'
    | '/channel'
    | '/income-details'
    | '/invite'
    | '/leaderboard'
    | '/login'
    | '/mission'
    | '/profile'
    | '/recharge'
    | '/redeem'
    | '/register'
    | '/team'
    | '/team-view'
    | '/test-headers'
    | '/transactions'
    | '/treasure-box'
    | '/vip-bonus'
    | '/withdraw'
    | '/withdrawals'
    | '/admin/gateways'
    | '/admin/login'
    | '/admin/members'
    | '/admin/payouts'
    | '/admin/plans'
    | '/admin/recharges'
    | '/admin/redeem-codes'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/transactions'
    | '/admin/withdrawals'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-bank'
    | '/admin'
    | '/app-download'
    | '/channel'
    | '/income-details'
    | '/invite'
    | '/leaderboard'
    | '/login'
    | '/mission'
    | '/profile'
    | '/recharge'
    | '/redeem'
    | '/register'
    | '/team'
    | '/team-view'
    | '/test-headers'
    | '/transactions'
    | '/treasure-box'
    | '/vip-bonus'
    | '/withdraw'
    | '/withdrawals'
    | '/admin/gateways'
    | '/admin/login'
    | '/admin/members'
    | '/admin/payouts'
    | '/admin/plans'
    | '/admin/recharges'
    | '/admin/redeem-codes'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/transactions'
    | '/admin/withdrawals'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddBankRoute: typeof AddBankRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppDownloadRoute: typeof AppDownloadRoute
  ChannelRoute: typeof ChannelRoute
  IncomeDetailsRoute: typeof IncomeDetailsRoute
  InviteRoute: typeof InviteRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MissionRoute: typeof MissionRoute
  ProfileRoute: typeof ProfileRoute
  RechargeRoute: typeof RechargeRoute
  RedeemRoute: typeof RedeemRoute
  RegisterRoute: typeof RegisterRoute
  TeamRoute: typeof TeamRoute
  TeamViewRoute: typeof TeamViewRoute
  TestHeadersRoute: typeof TestHeadersRoute
  TransactionsRoute: typeof TransactionsRoute
  TreasureBoxRoute: typeof TreasureBoxRoute
  VipBonusRoute: typeof VipBonusRoute
  WithdrawRoute: typeof WithdrawRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-bonus': {
      id: '/vip-bonus'
      path: '/vip-bonus'
      fullPath: '/vip-bonus'
      preLoaderRoute: typeof VipBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasure-box': {
      id: '/treasure-box'
      path: '/treasure-box'
      fullPath: '/treasure-box'
      preLoaderRoute: typeof TreasureBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-headers': {
      id: '/test-headers'
      path: '/test-headers'
      fullPath: '/test-headers'
      preLoaderRoute: typeof TestHeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-view': {
      id: '/team-view'
      path: '/team-view'
      fullPath: '/team-view'
      preLoaderRoute: typeof TeamViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-details': {
      id: '/income-details'
      path: '/income-details'
      fullPath: '/income-details'
      preLoaderRoute: typeof IncomeDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-download': {
      id: '/app-download'
      path: '/app-download'
      fullPath: '/app-download'
      preLoaderRoute: typeof AppDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-bank': {
      id: '/add-bank'
      path: '/add-bank'
      fullPath: '/add-bank'
      preLoaderRoute: typeof AddBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sliders': {
      id: '/admin/sliders'
      path: '/sliders'
      fullPath: '/admin/sliders'
      preLoaderRoute: typeof AdminSlidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redeem-codes': {
      id: '/admin/redeem-codes'
      path: '/redeem-codes'
      fullPath: '/admin/redeem-codes'
      preLoaderRoute: typeof AdminRedeemCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharges': {
      id: '/admin/recharges'
      path: '/recharges'
      fullPath: '/admin/recharges'
      preLoaderRoute: typeof AdminRechargesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gateways': {
      id: '/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AdminGatewaysRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGatewaysRoute: typeof AdminGatewaysRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRechargesRoute: typeof AdminRechargesRoute
  AdminRedeemCodesRoute: typeof AdminRedeemCodesRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlidersRoute: typeof AdminSlidersRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGatewaysRoute: AdminGatewaysRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRechargesRoute: AdminRechargesRoute,
  AdminRedeemCodesRoute: AdminRedeemCodesRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlidersRoute: AdminSlidersRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddBankRoute: AddBankRoute,
  AdminRoute: AdminRouteWithChildren,
  AppDownloadRoute: AppDownloadRoute,
  ChannelRoute: ChannelRoute,
  IncomeDetailsRoute: IncomeDetailsRoute,
  InviteRoute: InviteRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MissionRoute: MissionRoute,
  ProfileRoute: ProfileRoute,
  RechargeRoute: RechargeRoute,
  RedeemRoute: RedeemRoute,
  RegisterRoute: RegisterRoute,
  TeamRoute: TeamRoute,
  TeamViewRoute: TeamViewRoute,
  TestHeadersRoute: TestHeadersRoute,
  TransactionsRoute: TransactionsRoute,
  TreasureBoxRoute: TreasureBoxRoute,
  VipBonusRoute: VipBonusRoute,
  WithdrawRoute: WithdrawRoute,
  WithdrawalsRoute: WithdrawalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
